# Generated by Django 5.1 on 2024-08-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categories', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='clothingitem',
            options={'verbose_name': 'clothingItems', 'verbose_name_plural': 'clothingItems'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'customers', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'listings', 'verbose_name_plural': 'listings'},
        ),
        migrations.AlterModelOptions(
            name='rentalrequest',
            options={'verbose_name': 'rentalrequests', 'verbose_name_plural': 'rentalrequests'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'reviews', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'transactions', 'verbose_name_plural': 'transactions'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='clothingitem',
            table='clothingItems',
        ),
        migrations.AlterModelTable(
            name='customers',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='listing',
            table='listings',
        ),
        migrations.AlterModelTable(
            name='rentalrequest',
            table='rentalrequests',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
    ]
